version: 0.2

        
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install awscli==1.22.97
      - pip install boto3==1.21.42
      - pip install sagemaker==2.86.2 
      - pip install protobuf==3.20.0rc2
      - pip install json5==0.9.6
  build:
    commands:
      - mkdir tmp_targz
      - cp Pipeline_Builder/Helper_Functions/code_uploader.py .
      - cp Pipeline_Builder/Helper_Functions/ipynb_to_py.py .
      - python code_uploader.py
      - python ipynb_to_py.py --input_file Pipeline_Builder/Training_Pipeline_Builder.ipynb --output_file Training_Pipeline_Builder.py
      - python Training_Pipeline_Builder.py   
      - python ipynb_to_py.py --input_file Pipeline_Builder/Scoring_Pipeline_Builder.ipynb --output_file Scoring_Pipeline_Builder.py
      - python Scoring_Pipeline_Builder.py
      - python ipynb_to_py.py --input_file Pipeline_Builder/Monitoring.ipynb --output_file Monitoring.py
      - python Monitoring.py
artifacts:
  files:
    - '**/*'